# This version of docker-compose will start dnscrypt-proxy-2-docker at '172.172.172.53'.
# Point your DNS servers in NetworkManager or /etc/resolv.conf to '172.172.172.53'.
# When removing the comment hashes: make sure the line shifts left by 1 character.
# Uncomment 'ports:' to listen on localhost port 53 (0.0.0.0:53); fails when port 53 on localhost is already bound.
# uncomment 'volumes:' to specify a custom dnscrypt-proxy.toml
version: '3.3'
services:
    dnscrypt-proxy:
#        ports:
#           - '53:53/udp'
#        volumes:
#           - '/path/to/dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml'
        image: xtr0py/dnscrypt-proxy-2-docker
        networks:
            dnscrypt_network:
                ipv4_address: 172.172.172.53
        restart: always
networks:
    dnscrypt_network:
        ipam:
            driver: default
            config:
                - subnet: "172.172.172.0/24"
